In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import scipy.integrate

In [23]:
df = pd.read_csv("/media/sf_Ubuntu/share/stock4newtunesummer.csv")
df

          t_start_Buf       m468
0    26/06/2017 03:37   0.945139
1    26/06/2017 03:37   1.193680
2    26/06/2017 03:37   1.477220
3    26/06/2017 03:37   1.645240
4    26/06/2017 03:37   0.742109
5    26/06/2017 03:37   4.606680
6    26/06/2017 03:37   0.000000
7    26/06/2017 03:37   3.686040
8    26/06/2017 03:37   0.857627
9    26/06/2017 03:37   0.717606
10   26/06/2017 03:37   2.653390
11   26/06/2017 03:37   0.000000
12   26/06/2017 03:37   1.729250
13   26/06/2017 03:37   2.464360
14   26/06/2017 03:37   1.799270
15   26/06/2017 03:37   0.000000
16   26/06/2017 03:37   1.043150
17   26/06/2017 03:37   0.000000
18   26/06/2017 03:37   3.094460
19   26/06/2017 03:37   4.281130
20   26/06/2017 03:37   3.328990
21   26/06/2017 03:37   0.574085
22   26/06/2017 03:37   5.964880
23   26/06/2017 03:37   1.960290
24   26/06/2017 03:37   0.150522
25   26/06/2017 03:37   2.054800
26   26/06/2017 03:37   4.862220
27   26/06/2017 03:37   5.184260
28   26/06/2017 03:37   0.238035
29   26/06/2017 03:37   2.807410
..                ...        ...
620  26/06/2017 03:47   8.422240
621  26/06/2017 03:47  13.081400
622  26/06/2017 03:47   5.121260
623  26/06/2017 03:47  12.878400
624  26/06/2017 03:47   8.327730
625  26/06/2017 03:47   6.791000
626  26/06/2017 03:47   7.921670
627  26/06/2017 03:47   9.101340
628  26/06/2017 03:47  12.024300
629  26/06/2017 03:47  12.076800
630  26/06/2017 03:47  11.639200
631  26/06/2017 03:47   7.477100
632  26/06/2017 03:47  11.866800
633  26/06/2017 03:47  12.745400
634  26/06/2017 03:47  11.145600
635  26/06/2017 03:47   9.066340
636  26/06/2017 03:47  14.520100
637  26/06/2017 03:47   9.657930
638  26/06/2017 03:47  10.774600
639  26/06/2017 03:47  14.656700
640  26/06/2017 03:47   9.832950
641  26/06/2017 03:47  10.410500
642  26/06/2017 03:47   9.703430
643  26/06/2017 03:47   9.108340
644  26/06/2017 03:48   8.838810
645  26/06/2017 03:48  12.787400
646  26/06/2017 03:48  11.366200
647  26/06/2017 03:48   5.544820
648  26/06/2017 03:48   5.982380
649  26/06/2017 03:48  12.335800

[650 rows x 2 columns]

In [43]:
scipy.integrate.cumtrapz(df['m468'],x=None, dx=650.0)
y_int = scipy.integrate.cumptrapz('m468','utc',initial=0)

AttributeError: module 'scipy.integrate' has no attribute 'cumptrapz'

In [57]:
integral = np.trapz(df['m468'],x=None,dx=1.0, axis = -1)
integral

18679.1165415

In [ ]:
mix1 =